import 'jquery3'
import '../../../../vendor/assets/javascripts/jquery-ui/widgets/datepicker'
import '../../../../vendor/assets/javascripts/jquery-ui/widgets/dialog'
import '../../../../vendor/assets/javascripts/jquery-ui/widgets/sortable'
import '../../../../vendor/assets/javascripts/jquery-ui/widgets/tabs'
import '../../../../vendor/assets/javascripts/jquery-ui/widget'
import 'jquery_ujs'
// require_self
import './ext/jquery'
import './ext/jquery-ui'
import './lib/active_admin'
import './lib/batch_actions'
import './lib/dropdown-menu'
import './lib/has_many'
import './lib/modal_dialog'
import './lib/per_page'
import './lib/checkbox-toggler'
import './lib/table-checkbox-toggler'
import './initializers/datepicker'
import './initializers/filters'
import './initializers/tabs'

window.ActiveAdmin = {}
